sudo: false
language: d

matrix:
  include:
    - d: dmd-nightly
    - d: dmd
    - d: ldc
  allow_failures:
    - d: dmd-nightly

script:
  - dub test -b unittest-cov --compiler=${DC}

after_success:
  - bash <(curl -s https://codecov.io/bash)
