sudo: false
dist: trusty
language: d

d:
  - dmd
  - ldc

addons:
  apt:
    packages:
      - gcc-multilib
      - libx11-dev
      - libx11-dev:i386
      - zlib1g-dev
      - zlib1g-dev:i386

script:
  - dub test --compiler=${DC}
  - dub build --compiler=${DC}
